import { motion } from 'framer-motion'
import { ArrowLeft, Download, CheckCircle, XCircle, Lightbulb, Brain, BarChart2 } from 'lucide-react'
import { CircularScore } from '../components/results/CircularScore'
import { ScoreBar }      from '../components/results/ScoreBar'
import { SkillsChart }   from '../components/results/SkillsChart'

function SkillTag({ skill, type }) {
  const cls = type === 'matched' ? 'tag-matched' : type === 'missing' ? 'tag-missing' : 'tag-neutral'
  return (
    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium ${cls} transition-all hover:scale-105`}>
      {skill.name}
      {skill.category && (
        <span className="opacity-40 font-mono text-[9px]">{skill.category.split('/')[0].slice(0,5)}</span>
      )}
    </span>
  )
}

function Section({ title, icon, count, countType, children }) {
  const countStyle = countType === 'green'
    ? { background: 'var(--green-light)', color: 'var(--green)', border: '1px solid #B7DFC8' }
    : countType === 'red'
    ? { background: 'var(--red-light)', color: 'var(--red)', border: '1px solid #F5C6C2' }
    : { background: 'var(--cream-2)', color: 'var(--ink-3)', border: '1px solid var(--border)' }

  return (
    <div className="card overflow-hidden">
      <div className="px-5 py-4 flex items-center gap-2.5" style={{ borderBottom: '1px solid var(--border)' }}>
        {icon}
        <span className="font-semibold text-sm flex-1" style={{ color: 'var(--ink)' }}>{title}</span>
        {count !== undefined && (
          <span className="text-xs font-mono px-2 py-0.5 rounded-full" style={countStyle}>{count}</span>
        )}
      </div>
      <div className="p-5">{children}</div>
    </div>
  )
}

function downloadReport(r) {
  const lines = [
    '══════════════════════════════════════════',
    '  Resume Analyzer — Analysis Report',
    '══════════════════════════════════════════',
    '', `Analysis ID:  ${r.analysisId}`,
    `Job Field:    ${r.jobField}`,
    `Domain:       ${r.jobDomain}`,
    `Domain Fit:   ${r.domainMatch}`,
    `Processed in: ${r.processingTimeMs}ms`,
    '',
    '── SCORES ───────────────────────────────',
    `Match Score:     ${r.matchScore}%`,
    `ATS Score:       ${r.atsScore} / 100`,
    `Keyword Density: ${r.keywordDensity}%`,
    '',
    `── MATCHED SKILLS (${r.matchedSkills?.length}) ──────────────`,
    ...(r.matchedSkills?.map(s => `  ✓ ${s.name} [${s.category}]`) ?? []),
    '',
    `── MISSING SKILLS (${r.missingSkills?.length}) ──────────────`,
    ...(r.missingSkills?.map(s => `  ✗ ${s.name} [${s.category}]`) ?? []),
    '',
    '── SUGGESTIONS ──────────────────────────',
    ...(r.suggestions?.map((s,i) => `${i+1}. ${s}`) ?? []),
    '',
    `── YOUR RESUME SKILLS (${r.resumeSkills?.length}) ───────────`,
    ...(r.resumeSkills?.map(s => `  · ${s.name}`) ?? []),
    '',
    'Generated by Resume Analyzer (Java Spring Boot)',
  ]
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = `resume-analysis-${r.analysisId}.txt`
  a.click()
}

export function ResultsPage({ result, onBack }) {
  if (!result) return null
  const domainPct = result.domainMatch === 'High' ? 90 : result.domainMatch === 'Medium' ? 55 : 25

  return (
    <div style={{ background: 'var(--cream)', minHeight: '100vh' }} className="pt-16 pb-16 px-4 sm:px-6">
      <div className="max-w-6xl mx-auto">

        {/* Top bar */}
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
          className="flex items-center justify-between py-6 flex-wrap gap-3">
          <button onClick={onBack}
            className="flex items-center gap-1.5 text-sm font-medium transition-colors"
            style={{ color: 'var(--ink-3)', background: 'none', border: 'none', cursor: 'pointer' }}
            onMouseEnter={e => e.currentTarget.style.color = 'var(--ink)'}
            onMouseLeave={e => e.currentTarget.style.color = 'var(--ink-3)'}>
            <ArrowLeft className="w-4 h-4" /> Back to Analyzer
          </button>
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-xs px-2.5 py-1 rounded-full font-mono"
              style={{ background: 'var(--cream-2)', color: 'var(--ink-3)', border: '1px solid var(--border)' }}>
              {result.jobField}
            </span>
            <span className="text-xs px-2.5 py-1 rounded-full font-mono"
              style={{ background: 'var(--cream-2)', color: 'var(--ink-3)', border: '1px solid var(--border)' }}>
              Domain: {result.domainMatch}
            </span>
            <span className="text-xs px-2.5 py-1 rounded-full font-mono"
              style={{ background: 'var(--cream-2)', color: 'var(--ink-3)', border: '1px solid var(--border)' }}>
              {result.processingTimeMs}ms
            </span>
            <button onClick={() => downloadReport(result)}
              className="flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-lg transition-all"
              style={{ background: 'var(--ink)', color: '#fff', border: 'none', cursor: 'pointer', fontFamily: 'Geist, sans-serif' }}>
              <Download className="w-3.5 h-3.5" /> Download Report
            </button>
          </div>
        </motion.div>

        {/* ── SCORE ROW ── */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-5">
          {/* ATS ring */}
          <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
            className="card p-6 flex flex-col items-center justify-center">
            <p className="text-xs font-mono uppercase tracking-wider mb-4"
              style={{ color: 'var(--ink-4)' }}>ATS Score</p>
            <CircularScore value={result.atsScore} label="Compatibility" size={130} />
          </motion.div>

          {/* Match % */}
          <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.06 }} className="card p-5">
            <ScoreBar value={result.matchScore} label="Skill Match"
              sublabel={`${result.matchedSkills?.length ?? 0} of ${result.jdSkills?.length ?? 0} skills`} />
          </motion.div>

          {/* Keyword density */}
          <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }} className="card p-5">
            <ScoreBar value={result.keywordDensity} label="Keyword Density"
              sublabel="JD keywords in resume" />
          </motion.div>

          {/* Domain fit */}
          <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.14 }} className="card p-5">
            <ScoreBar value={domainPct} label="Domain Fit"
              sublabel={result.jobDomain} suffix="" />
          </motion.div>
        </div>

        {/* ── SKILLS ROW ── */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-4">
          <Section title="Matched Skills" countType="green" count={result.matchedSkills?.length ?? 0}
            icon={<CheckCircle className="w-4 h-4" style={{ color: 'var(--green)' }} />}>
            {result.matchedSkills?.length
              ? <div className="flex flex-wrap gap-2">{result.matchedSkills.map((s,i) => <SkillTag key={i} skill={s} type="matched" />)}</div>
              : <Empty icon="🎯" text="No matched skills found." />}
          </Section>

          <Section title="Missing Skills" countType="red" count={result.missingSkills?.length ?? 0}
            icon={<XCircle className="w-4 h-4" style={{ color: 'var(--red)' }} />}>
            {result.missingSkills?.length
              ? <div className="flex flex-wrap gap-2">{result.missingSkills.map((s,i) => <SkillTag key={i} skill={s} type="missing" />)}</div>
              : <Empty icon="🎉" text="No skill gaps — excellent match!" />}
          </Section>
        </div>

        {/* ── CHART + SUGGESTIONS ── */}
        <div className="grid grid-cols-1 lg:grid-cols-5 gap-4 mb-4">
          <Section title="Skills by Category" className="lg:col-span-2"
            icon={<BarChart2 className="w-4 h-4" style={{ color: 'var(--ink-3)' }} />}>
            <SkillsChart matched={result.matchedSkills ?? []} missing={result.missingSkills ?? []} />
          </Section>

          <div className="lg:col-span-3">
            <Section title="Recommendations"
              icon={<Lightbulb className="w-4 h-4" style={{ color: '#D97706' }} />}>
              {result.suggestions?.length
                ? <div className="flex flex-col gap-2.5">
                    {result.suggestions.map((s,i) => (
                      <motion.div key={i} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.05 }}
                        className="flex gap-3 rounded-xl p-3.5 transition-colors"
                        style={{ background: 'var(--cream)', border: '1px solid var(--border)' }}
                        onMouseEnter={e => e.currentTarget.style.background = '#fff'}
                        onMouseLeave={e => e.currentTarget.style.background = 'var(--cream)'}>
                        <span className="text-base flex-shrink-0">{s.slice(0,2)}</span>
                        <span className="text-sm leading-relaxed" style={{ color: 'var(--ink-2)' }}>{s.slice(2).trim()}</span>
                      </motion.div>
                    ))}
                  </div>
                : <Empty icon="💭" text="No suggestions." />}
            </Section>
          </div>
        </div>

        {/* ── ALL RESUME SKILLS ── */}
        <Section title={`All Skills in Your Resume`} count={result.resumeSkills?.length ?? 0}
          countType="neutral"
          icon={<Brain className="w-4 h-4" style={{ color: 'var(--ink-3)' }} />}>
          {result.resumeSkills?.length
            ? <div className="flex flex-wrap gap-2">{result.resumeSkills.map((s,i) => <SkillTag key={i} skill={s} type="neutral" />)}</div>
            : <Empty icon="📄" text="No recognizable skills found in your resume." />}
        </Section>

      </div>
    </div>
  )
}

function Empty({ icon, text }) {
  return (
    <div className="text-center py-8" style={{ color: 'var(--ink-4)' }}>
      <div className="text-3xl mb-2 opacity-40">{icon}</div>
      <p className="text-sm">{text}</p>
    </div>
  )
}
